@startuml
left to right direction
actor Utilisateur as User

usecase "Consulter les films recommandés" as consultMovies
usecase "Consulter les notes" as consultRatings
usecase "Notez des films" as manageMovies

User -- consultMovies
User -- manageMovies

consultMovies <.. consultRatings : <<extends>>

@end uml
