@startuml
left to right direction

class Film {
  +id: int
  +titre: string
}

class Avis {
  +id: int
  +note: int
}

class Tag {
  +id: int
  +nom: string
}

class Genre {
  +id: int
  +nom: string
}

class Utilisateur {
  +id: int
  +identifiant: string
  +motDePasse: string
}

Film "0..*" *-- "1" Avis
Avis "1" *-- "0..*" Utilisateur
Film "1..*" -- "1..*" Genre
Film "0..*" *-- "1" Tag

@enduml