@startuml
left to right direction
package "Système" {


rectangle "Système d'utilisation" as GD
rectangle "Serveur de recommandation" as SR

}

actor Utilisateur as User

database "Base de Données Postgres" as DB
database "Base de Données NoSql" as DB2



User-->GD
GD<--DB
GD<--DB2
GD->SR
@enduml
