@startuml
left to right direction
actor Administrateur as Admin

usecase "Gérer des films" as manageMovies
usecase "Gérer des utilisateurs" as manageUsers
usecase "Ajouter des films" as addMovies
usecase "Supprimer des films" as removeMovies
usecase "Supprimer des utilisateurs" as removeUsers
usecase "Supprimer des recommandations" as removeRecommendations

Admin --> manageMovies
Admin --> manageUsers

manageMovies <|-- addMovies
manageMovies <|-- removeMovies

manageUsers <|-- removeUsers
manageUsers <|-- removeRecommendations
@enduml
