@startuml
left to right direction

node "Serveur Backend" {
    component "Service Java (JPA/REST/WebSocket)" {
        database "Base de données relationnelle"
        database "Base de données NoSQL"
    }
}

node "Service De recommandation (Python)" {
    component "Moteur de recommandation"
    note right of "Moteur de recommandation"
        Utilise des algorithmes de filtrage collaboratif et des techniques de confidentialité
    end note
    component "Moteur de recommandation à froid"
}

node "API Gateway" {
    component "Orchestration et point d'entrée"
    interface "Interaction avec le Front-End"
    interface "Communication avec le Serveur Backend (Quarkus)"
    interface "Communication avec le Serveur Recommandation (Python)"
}

node "Poste Utilisateur" {
    component "Interface utilisateur"
}

@enduml